// <auto-generated />
using System;
using AspNetCoreWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreWebApp.Migrations
{
    [DbContext(typeof(m_db1Context))]
    [Migration("20220321111444_Migration_2022_03_21_5")]
    partial class Migration_2022_03_21_5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNetCoreWebApp.Models.MRelMT1MT2", b =>
                {
                    b.Property<long>("MId")
                        .HasColumnType("bigint")
                        .HasColumnName("m_id");

                    b.Property<long>("MT1MId")
                        .HasColumnType("bigint")
                        .HasColumnName("m_t1_m_id");

                    b.Property<long>("MT2MId")
                        .HasColumnType("bigint")
                        .HasColumnName("m_t2_m_id");

                    b.HasKey("MId")
                        .HasName("PK_m_rel_m_t1_m_t2_1");

                    b.HasIndex(new[] { "MT1MId" }, "m_t1_m_id");

                    b.HasIndex(new[] { "MT2MId" }, "m_t2_m_id");

                    b.ToTable("m_rel_m_t1_m_t2", (string)null);
                });

            modelBuilder.Entity("AspNetCoreWebApp.Models.MT1", b =>
                {
                    b.Property<long>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("m_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MId"), 1L, 1);

                    b.Property<string>("MC1Text")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("m_c1_text");

                    b.Property<decimal?>("MC2Decimal")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("m_c2_decimal");

                    b.Property<DateTime?>("MC3Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("m_c3_date");

                    b.HasKey("MId");

                    b.ToTable("m_t1", (string)null);
                });

            modelBuilder.Entity("AspNetCoreWebApp.Models.MT2", b =>
                {
                    b.Property<long>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("m_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MId"), 1L, 1);

                    b.Property<string>("MC1Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("m_c1_text");

                    b.HasKey("MId");

                    b.ToTable("m_t2", (string)null);
                });

            modelBuilder.Entity("AspNetCoreWebApp.Models.MT3", b =>
                {
                    b.Property<long>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("m_id");

                    b.Property<long>("MT1MId")
                        .HasColumnType("bigint")
                        .HasColumnName("m_t1_m_id");

                    b.Property<string>("MText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("m_text");

                    b.HasKey("MId")
                        .HasName("PK_t3");

                    b.ToTable("m_t3", (string)null);
                });

            modelBuilder.Entity("AspNetCoreWebApp.Models.MV1", b =>
                {
                    b.Property<decimal?>("MC2Decimal")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("m_c2_decimal");

                    b.Property<DateTime?>("MC3Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("m_c3_date");

                    b.Property<long?>("MId1")
                        .HasColumnType("bigint")
                        .HasColumnName("m_id_1");

                    b.Property<long?>("MId2")
                        .HasColumnType("bigint")
                        .HasColumnName("m_id_2");

                    b.Property<long?>("MId3")
                        .HasColumnType("bigint")
                        .HasColumnName("m_id_3");

                    b.Property<long?>("MT1MId")
                        .HasColumnType("bigint")
                        .HasColumnName("m_t1_m_id");

                    b.Property<long?>("MT2MId")
                        .HasColumnType("bigint")
                        .HasColumnName("m_t2_m_id");

                    b.ToView("m_v_1");
                });

            modelBuilder.Entity("AspNetCoreWebApp.Models.MRelMT1MT2", b =>
                {
                    b.HasOne("AspNetCoreWebApp.Models.MT1", "MT1M")
                        .WithMany("MRelMT1MT2s")
                        .HasForeignKey("MT1MId")
                        .IsRequired()
                        .HasConstraintName("FK_4");

                    b.HasOne("AspNetCoreWebApp.Models.MT2", "MT2M")
                        .WithMany("MRelMT1MT2s")
                        .HasForeignKey("MT2MId")
                        .IsRequired()
                        .HasConstraintName("FK_2");

                    b.Navigation("MT1M");

                    b.Navigation("MT2M");
                });

            modelBuilder.Entity("AspNetCoreWebApp.Models.MT3", b =>
                {
                    b.HasOne("AspNetCoreWebApp.Models.MT1", "MIdNavigation")
                        .WithOne("MT3")
                        .HasForeignKey("AspNetCoreWebApp.Models.MT3", "MId")
                        .IsRequired()
                        .HasConstraintName("FK_t3_t3");

                    b.Navigation("MIdNavigation");
                });

            modelBuilder.Entity("AspNetCoreWebApp.Models.MT1", b =>
                {
                    b.Navigation("MRelMT1MT2s");

                    b.Navigation("MT3")
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCoreWebApp.Models.MT2", b =>
                {
                    b.Navigation("MRelMT1MT2s");
                });
#pragma warning restore 612, 618
        }
    }
}
