apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcorewebapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetcorewebapp
  template:
    metadata:
      labels:
        app: aspnetcorewebapp
    spec:
      containers:
        - name: aspnetcorewebapp
          image: p2972014/aspnetcorewebapp_linux          
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcorewebapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: aspnetcorewebapp
  ports:
  - name: aspnetcorewebapp
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcorewebapp-nodeport
spec:
  type: NodePort
  selector:
    app: aspnetcorewebapp
  ports:
    - name: aspnetcorewebapp
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnetcorewebapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aspnetcorewebapp-clusterip
            port:
              number: 8095