apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcorewebapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetcorewebapi
  template:
    metadata:
      labels:
        app: aspnetcorewebapi
    spec:
      containers:
        - name: aspnetcorewebapi
          image: aspnetcorewebapi
          imagePullPolicy: IfNotPresent # загрузка образа из локального хранилища https://kubernetes.io/docs/concepts/containers/images/#updating-images
          ports:
            - containerPort: 80
---
# не обязательно для доступа извне
apiVersion: v1
kind: Service
metadata:
# может использоваться в url для доступа внутри сети, например http://aspnetcorewebapi-clusterip
  name: aspnetcorewebapi-clusterip 
spec:
  type: ClusterIP
  selector:
    app: aspnetcorewebapi
  ports:
  - name: aspnetcorewebapi
    protocol: TCP
    port: 80 # порт доступа к этому сервису внутри сети
    targetPort: 80 # порт приложения (kind: Deployment)
---
# для доступа с локального ПК
    # https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-ports-targetport-nodeport-service.html
    # https://www.bmc.com/blogs/kubernetes-port-targetport-nodeport/
    # https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
apiVersion: v1
kind: Service
metadata:
  name: aspnetcorewebapi-nodeport # может использоваться в url для доступа внутри сети, например http://aspnetcorewebapi-nodeport
    # https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields
    # https://devops.stackexchange.com/a/2446
spec:
  type: NodePort
  selector:
    app: aspnetcorewebapi
  ports:
    - name: aspnetcorewebapi
      protocol: TCP
      port: 80 # порт доступа к этому сервису внутри сети
      targetPort: 80 # порт приложения (kind: Deployment)
      nodePort: 32502 # порт для доступа с локального ПК
---
# не обязательно для доступа извне
    # https://kubernetes.io/docs/concepts/services-networking/ingress/
    # https://stackoverflow.com/questions/56243121/can-i-set-custom-ports-for-a-kubernetes-ingress-to-listen-on-besides-80-443
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnetcorewebapi-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:  
  rules:
  - 
    # host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aspnetcorewebapi-clusterip
            port:
              number: 80